name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'ubuntu-latest'
            args: ''
          - platform: 'windows-latest'
            args: '--target x86_64-pc-windows-msvc'
          - platform: 'windows-latest'
            args: '--target i686-pc-windows-msvc'
          - platform: 'windows-latest'
            args: '--target aarch64-pc-windows-msvc --bundles nsis'

    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        if: matrix.settings.platform == 'windows-latest'
        with:
          targets: "aarch64-pc-windows-msvc"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        if: matrix.settings.platform == 'macos-latest'
        with:
          targets: "aarch64-apple-darwin,x86_64-apple-darwin"

      - name: list targets
        run: rustup target list

      - name: install dependencies (ubuntu only)
        if: matrix.settings.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install dependencies
        run: pnpm install

      - name: copy files to @contentlayer/source-files
        if: matrix.settings.platform == 'windows-latest'
        run: |
          copy fixed_pkg\makeCacheItemFromFilePath.js node_modules\.pnpm\node_modules\@contentlayer\source-files\dist\fetchData\makeCacheItemFromFilePath.js

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.CYF_RELEASE_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          GIT_COMMIT_SHA: ${{ github.sha }}
          NEXT_PUBLIC_GOOGLE_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_ID }}
          # code signing for macos
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: v__VERSION__
          args: ${{ matrix.settings.args }}

  update_cask:
    runs-on: ubuntu-latest
    needs: publish

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          repository: cyf/homebrew-cyf
          token: ${{ secrets.CYF_HOMEBREW_FAFOREVER }}

      - name: Update Version
        run: |
          VERSION=$(echo "$TAG_NAME" | sed 's/^v//')
          # macOS
          # sed -i "" "s/version \"[^\"]*\"/version \"$VERSION\"/" Casks/faforever.rb
          sed -i "s/version \"[^\"]*\"/version \"$VERSION\"/" Casks/faforever.rb
        env:
          TAG_NAME: ${{github.ref_name}}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: ${{github.ref_name}}"
          commit_options: '--no-verify --signoff'
          commit_user_name: kjxbyz
          commit_user_email: kjxbyz888@outlook.com
          commit_author: kjxbyz <kjxbyz888@outlook.com>
          add_options: '-u'
          push_options: '--force'
